services:
  hugo-site:
    image: ghcr.io/michael-xkcd/mcmurray-tech:${MCMURRAY_TECH_IMAGE_TAG:-v0.1.1}
    container_name: mcmurray-tech
    restart: unless-stopped
    networks:
      - proxynet

networks:
  proxynet:
    external: true
